Algoritmo "antecessor_e_sucessor"
// Disciplina   : [Algoritmo e Lógica de Programação]
// Professor   :
// Descrição   : Mostrar antecessor e sucessor
// Autor(a)    : Nome do(a) aluno(a): Shelton Teles
// Data atual  : 8/20/2022
Var
num, ant, suc : inteiro

Inicio
num := 13
ant := num - 1
suc := num + 1

Escreval ("O antecessor do nr 13 é ", ant, " e o sucessor é, ", suc)
leia (ant)
leia (suc)


Fimalgoritmo