Algoritmo "teste1"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07-10-2022
Var
   // Seção de Declarações das variáveis
   i,j:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para i de 1 ate 3 passo 1 faca
      para j de 1 ate 6 passo 2 faca
         se j%i=0 entao
            escreva(i+j)
         fimse
      FIMPARA
      fimpara

Fimalgoritmo