Algoritmo "semnome"
// Disciplina   : [Algoritmo e Lógica de Programação]
// Professor   : 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 8/20/2022
Var
nr_de_estudantes, idade, maior_idade, menor_idade, i : inteiro


Inicio
i <- 1
Escreval ("Digite o número total de alunos: ")
leia (nr_de_estudantes)

  enquanto i <= 5  faça
    Escreval ("Insira a idade dos estudantes: ")
    leia (idade)
  fimenquanto


Fimalgoritmo