Algoritmo "31pares"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26-09-2022
Var
// Seção de Declarações das variáveis 
i,soma:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Os pares entre 85 e 907 são:")
soma<-0
i<-85
enquanto i<=907 faca
se i%2=0 entao
escreval(i)
soma<-i+soma

fimse
i<-1+i
fimenquanto
escreval(soma)


Fimalgoritmo