Algoritmo "33rainha"
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26-09-2022
Var
// Seção de Declarações das variáveis 
 i,g,a,soma:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
i<-1
a<-1
soma<-0
enquanto i<=5 faca
g<-a*2
a<-g
soma<-a
i<-1+i
fimenquanto

 escreval((soma-1))
Fimalgoritmo