Algoritmo "41umadez"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30-09-2022
Var
// Seção de Declarações das variáveis 
     i,soma:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 i<-1
 soma<-0
 enquanto i<=10 faca
 
 soma<-i+soma
 i<-i+1

 fimenquanto

 escreval(soma)
Fimalgoritmo