Algoritmo "menor_ou_maiorquadrado"
// Disciplina   : [Algoritmo e Lógica de Programação]
// Professor   :
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 9/17/2022
Var

//variáveis

N,m,i: inteiro
raizN,qud: real
Inicio
 escreva("Digite um número: ")
leia(N)

i<-1
repita
   i<-1+i
   m<-i*i
   

ate  m>=n
i<-i-1
m<-i*i

escreva("O maior quadrado menor ou igual a",N," é", i,"",m)
fimalgoritmo