Algoritmo "produto1a15"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18-09-2022
Var
// Seção de Declarações das variáveis 
soma,i:inteiro;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
soma<-1
para i de 1 ate 15 passo 1 faca

 se (i%2)<>0 entao
 soma<-soma*i
 fimse
 

fimpara
escreval(soma," ")

Fimalgoritmo