Algoritmo "tabelaMultiplicar"

//37.Um determinado material radioativo
//perde metade de sua massa a cada 50 segundos.
//Dada a massa inicial, em gramas,
//faça um programa que determine o tempo necessário
//para que essa massa se torne menor que 0,05 gramas.
VAR i,n,resu:inteiro;

Inicio

 escreval("Tabela de multiplicação do número:")
 leia(n)
 
 para i de 1 ate 13 passo 1 faca
 resu<-n*i
 escreval(n,"x",i,"=",resu)
 
 fimpara

Fimalgoritmo