Algoritmo "soma_de_dois_numeros_inteiros"
// Disciplina   : [Programação]
// Professor   :  Rafael
// Descrição   : O programa deve exibir a soma de dois nr inteiros
// Autor(a)    : Shelton Teles Uamusse
// Data atual  : 8/27/2022
Var
x, y, soma: inteiro


Inicio
Escreval ("Digite um número: ")
leia (x)

Escreval ("Digite outro número: ")
leia (y)
soma := x+y
Escreva ("A soma dos números é ", soma)


Fimalgoritmo